### ISSUE TITLE
[PROPOSAL] AddArray method

### ISSUE THREAD

**Issue by lukasoppermann** [spatie/laravel-menu#10]
Hey,

as I am starting to use the package, it noticed that it would be pretty handy to be able to loop over an array. Pretty often menu items will be stored in a config file or a database and retrieved in one set. While it is possible to achieve this by hand or using a macro, I think it would be a valuable addition to the package (probably added to the main package, nor the Laravel version).

To allow for as much flexibility and little code, I would suggest to add a method that takes an `array` and a `callable` as parameters, the callable gets the `$key` and `$value` and needs to return an `Item`.

I used the macro function to build a "prototype" but I think it would be much better to include this into the default build.

```php
Menu::macro('addArray', function(array $array, callable $callable){
    foreach($array as $key => $value)
    {
        $this->add($callable($value, $key));
    }
    return $this;
});

// will be use like this:

return Menu::new()
    ->addArray([
        [
            'link' => '/link',
            'name' => 'Link'
        ],
        [
            'link' => '/link-2',
            'name' => '2nd Link'
        ],
    ], function($item){
        return Link::to($item['link'], $item['name']);
    });
```

**Comment by danhunsaker** [comment]
Nested menus would need to be accounted for as well.

**Comment by lukasoppermann** [comment]
Well, I would not say they would necessarily need to be accounted for, you could probably do this by hand in the closure. Otherwise how would the package figure out what is a submenu item? I think this would put to much complexity into the package.

**Comment by sebastiandedeyne** [comment]
I deliberately left out a method like this because there are so many ways to do it, and it's pretty trivial to implement it in your own code (e.g. as a macro like you posted).

For example, you provided an array like `[ ['link' => '...', 'name' => '...' ], ... ]`, while other people might prefer an array like `[ <link> => <name>, <link> => <name>, ... ]`. And then there are multiple ways to handle things like html attributes and submenus too.

In your example a method parameter is provided as an extra argument to circumvent any array format limitation, but then you might as well reduce your array to a menu imo (that's what we're doing in our apps, also very useful for creating menus from items that come from the database).

```php
$menu = collect([
    [ 'link' => '/link', 'name' => 'Link' ],
    [ 'link' => '/link-2', 'name' => '2nd Link' ],
])->reduce(function ($menu, $item) {
    return $menu->link($item['link'], $item['name']);
}, Menu::new());
```

**Comment by lukasoppermann** [comment]
Hmm, I will try the collection `reduce` method, that looks good.

However I do not see how there are many ways to do this, as all the logic for adding an item to the menu should the handled in the closure. The package would only provide the method to loop over an array, thus allowing for a nice way to add those items in a fluent way.

I think this is very useful when you combine static and dynamic menu items in one menu.

**Comment by sebastiandedeyne** [comment]
I agree that having something like this inline could be valuable. I'll give it some thought :)

**Comment by lukasoppermann** [comment]
@sebastiandedeyne if you are giving this some though, could you maybe reopen the issue, so that it is not forgotten? Thank you.

**Comment by sebastiandedeyne** [comment]
v2 of the spatie/menu package will have a static `build` method, and a non-static `fill` method. Both will accept two parameters, an `$items` array (or `Iterator` instance), and a callable `$reducer`.

Example:

```php
$myNav = ['home' => 'Home', 'contact' => 'Contact'];

$menu = Menu::build($myNav, function ($menu, $label, $route) {
    return $menu->route($route, $label);
});
```

**Comment by lukasoppermann** [comment]
This is perfect, it works very well. I did not find any bugs.
