### ISSUE TITLE
where to put 'Menu::new()...'

### ISSUE THREAD

**Issue by larylinz** [spatie/laravel-menu#105]
Thank you for doing lovely stuff for Laravel!

I'm new to Laravel 8 and can't get a glue aut of the docs where to put for example:

Menu::new()
    ->url('/', 'Home')
    ->route('contact', 'Contact')
    ->action('PageController@about', 'About');

I couldn't find an working example...

**Comment by nickfls** [comment]
@larylinz really, wherever you want.

I suggest you look here; [spatie/menu documentation](https://spatie.be/docs/menu/v2/menus-in-your-laravel-app/using-macros)

Assuming you want a central spot for your menus (and this is an assumption, there are many strategies), you can do something like this:

in you `AppServiceProvider`:
```php
...
use Spatie\Menu\Laravel\Menu;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Menu::macro('main', function() {
            return Menu::new()
                        ->url('/', 'Home')
                        ->route('contact', 'Contact')
                        ->action('PageController@about', 'About');
        });
    }
```

this will register a a macro you can reuse in your views:
```php
<header>
    {!! Menu::main() !!}
</header>
```
Once you get a better understanding how laravel works, may I suggest you take a loot at:

- view components
- view composers
- event-based navigation builds
- middleware based navigation builds
