### ISSUE TITLE
Installation problem with required illuminate/auth

### ISSUE THREAD

**Issue by kagnara** [spatie/laravel-menu#106]
Hello,
I can't install spatie/laravel-menu

My environment is
- php 7.2
- laravel 6.*

>composer require spatie/laravel-menu
> ...
> `>` Your requirements could not be resolved to an installable set of packages.
> `>` Problem 1
>    - illuminate/auth v8.9.0 requires php ^7.3 -> your PHP version (7.2.34) does not satisfy that requirement.
>    - illuminate/auth v8.8.0 requires php ^7.3 -> your PHP version (7.2.34) does not satisfy that requirement.

**Comment by freekmurze** [comment]
Please upgrade to PHP 7.3

**Comment by kagnara** [comment]
If I don’t want to update php version is there anyway or any specific
version for php7.2?

**Comment by now2ali** [comment]
Same issues also i am facing

php 8.1
laravel 10.*

Problem 1
    - spatie/laravel-menu 3.6.0 requires php ^7.2 -> your php version (8.1.17) does not satisfy that requirement.
    - spatie/laravel-menu[3.7.0, ..., 3.7.1] require illuminate/auth ^7.24|^8.0 -> found illuminate/auth[v7.24.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires spatie/laravel-menu ^3.6 -> satisfiable by spatie/laravel-menu[3.6.0, 3.7.0, 3.7.1].
