### ISSUE TITLE
Problem install spatie/laravel-menu php7.2

### ISSUE THREAD

**Issue by kagnara** [spatie/laravel-menu#107]
Hello,
I can't install spatie/laravel-menu

My environment is

php 7.2
laravel 6.*
> composer require spatie/laravel-menu
> ...
> `>` Your requirements could not be resolved to an installable set of packages.
> `>` Problem 1
> illuminate/auth v8.9.0 requires php ^7.3 -> your PHP version (7.2.34) does not satisfy that requirement.
> illuminate/auth v8.8.0 requires php ^7.3 -> your PHP version (7.2.34) does not satisfy that requirement.

If I don’t want to update php version is there anyway or any specific
version for php7.2?

**Comment by freekmurze** [comment]
No, we don't support 7.2
