### ISSUE TITLE
Object of class View could not be converted to string

### ISSUE THREAD

**Issue by sgc-fireball** [spatie/laravel-menu#108]
Laravel-menu has currently issues with spatie/menu ~ 2.10.2

Object of class Spatie\Menu\Laravel\View could not be converted to string in 
vendor/spatie/menu/src/Menu.php:724

A downgrade to spatie/menu@2.9 solve it currently.

**Comment by freekmurze** [comment]
Our tests indicate that the package is working as intended. 

Could you please PR a failing test that demonstrates the bug?

**Comment by sgc-fireball** [comment]
`    /** @test */
    public function renderWithSpatieMenu2_10_2()
    {
        Menu::macro('admin', function () {
            $menu = Menu::new();
            $submenu = Menu::new();
            $menu->submenu(View::create('withActive', ['active' => false]), $submenu);
            return $menu;
        });
        Menu::admin()->toHtml();
        $this->assertTrue(true);
    }`

The Submenu header could not be rendert:

`1) Spatie\Menu\Laravel\Test\ViewTest::renderWithSpatieMenu2_10_2
Error: Object of class Spatie\Menu\Laravel\View could not be converted to string

spatie/laravel-menu/vendor/spatie/menu/src/Menu.php:724
spatie/laravel-menu/vendor/spatie/menu/src/Menu.php:766
spatie/laravel-menu/vendor/spatie/menu/src/Menu.php:716
spatie/laravel-menu/src/Menu.php:258
spatie/laravel-menu/tests/ViewTest.php:53`
