### ISSUE TITLE
Invalid scheme when using javascript

### ISSUE THREAD

**Issue by ChristinePHP** [spatie/laravel-menu#111]
I'm creating a new issue for the situation that arises whereby an invalid scheme error exception is thrown when having links that link to javascript, eg. javascript:void(0) AND when setActiveFromRequest() is used. Please see a detailed description of the error in the issue that was experienced by another user and that was closed due to not being able to duplicate the issue (ie. issue #99).

**Comment by sebastiandedeyne** [comment]
Solved in `3.7.1`
