### ISSUE TITLE
Add activateForPath method

### ISSUE THREAD

**Issue by lukasoppermann** [spatie/laravel-menu#16]
Hey @sebastiandedeyne,

as you might have noticed, I am using views for all my menu items. While I understand that this might not be the case for your projects, I think it is a very likely case for things like:

- profile links with `(img) Name`
- links prefixed with an inline/use svg
- links which have Additional elements, e.g. a list of links with a delete link on them as well

... and many more.

I do understand you do not want to alter and/or mess up the api, so something like `View::create('/link','view.name')` is out of the question.

My proposal would be to add a function `activateForPath` which could be used to set the link that should trigger the activation of a menu item.

The usage would be like this:

```php
View::create('view.name')->activateForPath('/link');
```

I think, all it would need to do would be the following:

```php
public function activateForPath($path)
{
    if(app('request')->path() === trim($path,'/')){
        $this->setActive();
    }

    return $this;
}
```

This would solve such a big headache, please, let us implement it. 😃

**Comment by sebastiandedeyne** [comment]
This would be a very elegant solution. I'm considering making some breaking change in the base `menu` package that would replace the current `HasUrl` implementation with this, and tagging 2.0 for it.

**Comment by lukasoppermann** [comment]
This would be awesome. I would love it, let me know if there is anything I can test.

**Comment by sebastiandedeyne** [comment]
The v2 version of spatie/menu now implements a `determinActiveForUrl` method on every `Activatable` item.

**Comment by lukasoppermann** [comment]
Sorry, could you explain how `determinActiveForUrl` works? I can't figure it out.

**Comment by sebastiandedeyne** [comment]
When determining if an item is active or not, it asks the item through the `determineActiveForUrl` method. By default, this method is a stub that does nothing. However, if the `HasUrl` trait is used, it will match the url to the request to determine the active state.

https://github.com/spatie/menu/blob/master/src/Traits/HasUrl.php#L43
