### ISSUE TITLE
[Suggestion] Fluent API for considering authorization

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/laravel-menu#2]
Originally posted by @themsaid here: https://github.com/spatie/menu/issues/1

```php
Menu::new()
    ->link('/', 'Home')
    ->linkIfCan('/products', 'Products', 'review_products');
    ->linkIfCan('/inventory', 'Inventory', ['check_inventory', 'update_inventory']);
```

**Comment by sebastiandedeyne** [comment]
Probably going to implement this soon, but still have some doubts on the details. Gonna post some random thoughts here—

- The base method should be `addIfCan`. Not sure what makes more sense for the parameter order, the permission or the item.

```php
Menu::new()
    ->addIfCan('review_products', Link::to('/products', 'Products'));
```

vs.

```php
Menu::new()
    ->addIfCan(Link::to('/products', 'Products'), 'review_products');
```

Leaning towards permission first.

- Since it's in a Laravel context, I'd like to be able to have `urlIfCan`, `routeIfCan` and `actionIfCan` alongside `linkifCan`, but this would quickly become a mess since they already require so many parameters.

- In the inventory example you used an array, Laravel doesn't support this by default right? It slightly bothers me is not knowing if the array means `and` or `or`.

**Comment by freekmurze** [comment]
+1 for having the permission as the first parameter.

To keep things simple you could only support a string. If there is a complex condition users could just register a new permission at the gate.

**Comment by themsaid** [comment]
Well my parameter ordering was based on plain english `Add (this Link) if can (this permission).`

I've been developing iOS apps in swift for a little while, what I miss from swift in PHP is the ability to name parameters.

```
func add(link: Link, ifUserCan ability: String) {}
```

You call it like that:

```
add(Link::mylink() ifUserCan: 'manage_orders')
```

**Comment by sebastiandedeyne** [comment]
WIP, lots of arguments there but don't really mind: https://github.com/spatie/laravel-menu/commit/bbfed88d0f9e1b35f9588c9eea6313311c81ea0e

The permission can be an array so you could pass arguments, e.g: 
```
$menu->linkIfCan(['edit-post', $post], ...)`
```

Need to do some minor refactoring and write tests, will release later this week.

**Comment by sebastiandedeyne** [comment]
Added in 1.1!

https://github.com/spatie/laravel-menu/releases/tag/1.1.0
