### ISSUE TITLE
FatalErrorException in MenuServiceProvider.php

### ISSUE THREAD

**Issue by mohamed-ibrahem** [spatie/laravel-menu#24]
while I publish my project I got this _error_,

**FatalErrorException in MenuServiceProvider.php line 12:
syntax error, unexpected 'new' (T_NEW)**

**Comment by freekmurze** [comment]
I see nothing wrong when looking at [that line of code](https://github.com/spatie/laravel-menu/blob/master/src/MenuServiceProvider.php#L12).

What version of the package / PHP / Laravel are you running?

Could you post the contents of `MenuServiceProvider.php` present in your project?
