### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ckwong** [spatie/laravel-menu#3]
run:  composer require spatie/laravel-menu

Found Error
[InvalidArgumentException]
  Could not find package spatie/laravel-menu at any version for your minimum-
  stability (stable). Check the package spelling or your minimum-stability

**Comment by freekmurze** [comment]
Do you have PHP 7 installed?

On Sunday, 27 March 2016, newbie2005 <notifications@github.com> wrote:

> run: composer require spatie/laravel-menu
>
> Found Error
> [InvalidArgumentException]
> Could not find package spatie/laravel-menu at any version for your minimum-
> stability (stable). Check the package spelling or your minimum-stability
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/spatie/laravel-menu/issues/3>
>


-- 
Freek Van der Herten
https://spatie.be
+32 495 84 27 91

**Comment by ckwong** [comment]
After install php7, fixed

**Comment by zanematthew** [comment]
Just for any others, I did have to `ssh` into my vagrant box and run the composer command.
