### ISSUE TITLE
route() method has only 3 args, 4 passed.

### ISSUE THREAD

**Issue by mathieutu** [spatie/laravel-menu#42]
Hi guys,
on your `$menu->route()` method, you consider 4 arguments, but at the end the `\Illuminate\Routing\UrlGenerator::route` accept only three.

Am I missing something, or the last parameter `\Illuminate\Routing\Route $route` is useless?

Thanks.
Matt'

<img width="837" alt="screen shot 2017-02-17 at 18 59 10" src="https://cloud.githubusercontent.com/assets/11351322/23077515/2bdaf644-f545-11e6-9d1d-c5c006c46f21.png">
<img width="1012" alt="screen shot 2017-02-17 at 18 57 19" src="https://cloud.githubusercontent.com/assets/11351322/23077518/2e22288c-f545-11e6-8c56-ac7fbcf061ad.png">

**Comment by sebastiandedeyne** [comment]
Apparently this used to be a thing: https://github.com/laravel/framework/pull/13206/files

Tagged a new release without the `$route` parameter!

**Comment by freekmurze** [comment]
Hey @mathieutu,

see you at Laracon EU this year?

**Comment by mathieutu** [comment]
Hi @freekmurze!
Obviously! What else? 😉
