### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Langstra** [spatie/laravel-menu#43]
I installed the plugin with composer, then added the provider and the facade. However, I still get an error
```
Class 'Menu' not found (View: /path/to/laravel/views/layouts/menu.blade.php
```
I added this to the providers array
```
Spatie\Menu\Laravel\MenuServiceProvider::class
```
And I added this to the aliasses array
```
'Menu' => Spatie\Menu\Laravel\MenuFacade::class
```

I am also using Barry's LaravelIdeHelper, which also does not pick up on the Menu class. I am unsure what I did wrong. Other plugins did install without problems and this time I did not do anything different. I already tried using an older version.

This is my composer.json
```
    "require": {
        "php": ">=5.6.4",
        "barryvdh/laravel-debugbar": "^2.3",
        "barryvdh/laravel-ide-helper": "^2.2",
        "laracasts/utilities": "~2.0",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "spatie/laravel-menu": "~2.1.2"
    },
```

**Comment by sebastiandedeyne** [comment]
That's odd. Could you try clearing the application's compiled classes?

```
php artisan clear-compiled
```

**Comment by Langstra** [comment]
Thanks, I tried that one, but that did not help. I already ran `composer update`, which does this as well I think.

**Comment by Langstra** [comment]
I found the solution. I am not sure why the error occurred exactly, but it was an issue with composer.
1. delete vendor folder
2. delete composer.lock file
3. run composer clearcache
4. run composer install

**Comment by sebastiandedeyne** [comment]
Computers ¯\\_(ツ)\_/¯

Glad to see you got it to work!
