### ISSUE TITLE
[Question] How to add Link with Form

### ISSUE THREAD

**Issue by faustbrian** [spatie/laravel-menu#44]
Is there any way to add a Menu Item that also contains a form that would be used by clicking on the menu item? Something like the following.

```
<li>
    <a onclick="event.preventDefault();document.getElementById('logout-form').submit();">
        @lang('logout')
    </a>

    <form id="logout-form" action="{{ route('logout') }}" method="DELETE" style="display: none;">
        {{ csrf_field() }}
    </form>
</li>
```

**Comment by sebastiandedeyne** [comment]
You can add a raw html item with the `html` method.

```php
Menu::html('<span>Hi!</span>');
```

```html
<ul>
  <li><span>Hi!</span></li>
</ul>
```

**Comment by faustbrian** [comment]
@sebastiandedeyne After some reading through the docs I found that the cleaner solution would be the following.

`->add(\Spatie\Menu\Laravel\View::create('front.auth._partials.logoutForm'))`

Thanks!
