### ISSUE TITLE
[Question] Only Adds Class to single/specific <li></li> List item only?

### ISSUE THREAD

**Issue by yelnyaface** [spatie/laravel-menu#46]
is it possible to add class to single `<li></li>` like `<li class="header">System</li>` only?  instead of ALL `<li></li>` ?

the only thing tht I know of add is -`>addItemParentClass()` 

is that the only method to add class to `<li>` only?

**Comment by sebastiandedeyne** [comment]
Adding classes to specific parents (`li`'s) isn't supported yet. I'll try to add this in the near future.

Closing this since it should be tracked in spatie/menu#38.
