### ISSUE TITLE
Documentation != source?

### ISSUE THREAD

**Issue by daedeloth** [spatie/laravel-menu#47]
I was reading:
https://docs.spatie.be/menu/v2/items-in-depth/active-items

```
$menu->setActive(function (Link $link) {
    if (\Request::segment(0) == $link->segment(1)) {
        return true;
    }
});
```

But this method segment() doesn't seem to exist.

I was looking through the versions but I can't seem to find that anywhere?
Is the documentation outdated?

Thanks!

**Comment by J5lx** [comment]
See also spatie/menu#26.

**Comment by introwit** [comment]
Hi :) It was dropped in the v2 of the package. We will update the docs about it, thanks.
