### ISSUE TITLE
[Feature Request] Set SubmenuHeader Active if it's the active link

### ISSUE THREAD

**Issue by etenzy** [spatie/laravel-menu#49]
When the active site is the SubmenuHeader, the li before the Link (and the path before) doesn't be set as active.
The same behavior can be noticed when the SubmenuHeader is a view...

It would solve a lot of my problems, if this would be added.

Use Case:
```php
Menu::new()
    ->submenu(
        Link::toRoute('routename', ''Link-Title'),
        Menu::new()
    )
    ->submenu(
        View::create('viewname', ['title' => 'Link-Title', 'url' => route('routename')]),
        Menu::new()
    )
```

**Comment by sebastiandedeyne** [comment]
Next time I do a feature update for this package I'll look into this. Can't promise that will be anytime soon though.

If someone needs this in the mean time, feel free to send a non-breaking, preferably tested PR to the spatie/menu package.
