### ISSUE TITLE
**[QUESTION]**: How do I display the menu on the blade template?

### ISSUE THREAD

**Issue by reypm** [spatie/laravel-menu#5]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [ ] I have checked that the bug-fix I am reporting can be replicated.

---

### How do I display the menu on the blade template?
I am trying to show the menu on the layout template after I built it using View Composer. This is the code I have in `resources/views/layout.blade.php`:

    <nav class="navigation">
        {!! Menu::main() !!}
    </nav> 

And I got this error:

> ErrorException in Macroable.php line 81:
> Method main does not exist. (View: /var/www/html/platform.local/resources/views/layout.blade.php) (View: /var/www/html/platform.local/resources/views/layout.blade.php)

I don't know if I am missing something here but is not working and I can't find in docs an example of this. If needed [this is](https://github.com/reypm/platform_islr) the repository I am working with and below is a list of the classes involve:

- [MenuComposer.php](https://github.com/reypm/platform_islr/blob/master/app/Http/ViewComposers/MenuComposer.php)
- [MenuRepository.php](https://github.com/reypm/platform_islr/blob/master/app/MenuRepository.php)
- [MenuBuilderProvider.php](https://github.com/reypm/platform_islr/blob/master/app/Providers/MenuBuilderProvider.php)

Can you give me some help? Maybe improve docs for newbies?

### Steps to reproduce 
Just clone the repository, run the migrations and seeds and try to open the page you should see the issue.

**Comment by sebastiandedeyne** [comment]
Since you're using a view composer, the menu will be passed in as a variable to your view.

```
$view->with('menus', $this->menus->generateMenu());
```

This creates a `menus` variable in your view, which would look like this:

```
{!! $menus !!}
```
