### ISSUE TITLE
[Feature Request] Add items to tagged positions

### ISSUE THREAD

**Issue by ttomdewit** [spatie/laravel-menu#51]
Dear Spatie team,

First of all thank you for all your hard work 👏.

I've been playing with laravel-menu for a bit now and figured out how to add items to the same menu from various sources:

- I added a 'test' link from within the Laravel app
- I added a 'package' link from within a custom Laravel package

I'm wondering if it would be useful, and in the scope of this package, to be able to add a menu item to a tagged position.

Painting a picture: let's say you are building your own docs sidebar menu. You could optionally "tag" a position called "Basic Usage". From anywhere in your code you could fetch your menu with `app('menu.docs.sidebar)` (pseudo-code) and `->link('random-link', 'Random Link');`. This would prepend the "Random Link" item to the sidebar menu, specifically under the "Basic Usage" list.

If this is already possible I've must've skipped the docs on that part. If this is not possible, I'd love to collaborate on the solution and possibly provide a Pull Request, if and when required.

Thank you for looking into this, and I'd love hearing from you.

Tom

**Comment by ttomdewit** [comment]
Dear Spatie team,

Any feedback on this issue? I'd love to hear from you.

Tom

**Comment by freekmurze** [comment]
Seems like a cool feature, my guess is that we would be open for a PR that adds this.

What do you think @sebastiandedeyne

**Comment by sebastiandedeyne** [comment]
Hi Tom, sorry for not getting back to this sooner!

What you could do now is instead of using a single menu, compose a menu consisting of various submenus. You could bind each submenu to the IoC, and use your proposed syntax as is?

Quick mockup of what that could look like:

```php
// In a service provider of some sorts...

$this->app->singleton('menu.docs.sidebar', function () {
    return Menu::create()->link('foo', 'bar');
});

$this->app->singleton('menu.docs', function () {
    return Menu::create()->submenu($this->app->make('menu.docs.sidebar'));
});

// Somewhere else in your application...
app('menu.docs.sidebar')->link('random-link', 'Random Link');
```

This would generate a different html structure though, but it depends on the context of your application if that matters or not.

If this wouldn't suffice, I'm open to adding an API for this. I don't think the codebase really allows inserting menu items at other spots without doing something hacky though, so it might be for v3 then...

**Comment by ttomdewit** [comment]
@sebastiandedeyne Thank you very much for coming back to this query and providing me with an example codebase to work with. I'll be giving this a shot over the coming week and if this does not satisfy our needs I will report back and gladly work with you on a V3 implementation.

Thank you for your time.

Tom

**Comment by sebastiandedeyne** [comment]
I'm open to adding this functionality via a PR, but we'd need to flesh out an API first.

**Comment by sebastiandedeyne** [comment]
Also, I think this should be added to the base menu package, not this one. If anyone has a proposal, please open an issue in that repo.

https://github.com/spatie/menu
