### ISSUE TITLE
How do I add menu items after the object is built?

### ISSUE THREAD

**Issue by willneumann** [spatie/laravel-menu#53]
I've registered my menu in a service provider like below (and as described in https://github.com/spatie/laravel-menu/issues/52), and I'm able to use it my views without issues.
`Menu::macro('main', function () {
   return Menu::new()
      ->add(Link::to('/', 'Home'))
      ->add(Link::to('/about', 'About'));
});`

However, if I'm adding items to the menu afterwards, let's say from a controller, it doesn't seem to add the items (and it's not giving me any error either). Here's the code I'm using in my controller:
`Menu::main()->add(Link::to('/contact', 'Contact'));`

Any idea how to add items to the menu after the object is built?

**Comment by sebastiandedeyne** [comment]
When you call your `main` macro, you're instantiating a new menu every time. You'll need to keep the menu in a variable, and somehow pass that variable along to your controller.

For example, you could bind the menu to the IoC container.

```
app()->instance('menu.main', Menu::main());

app('menu.main')->add(Link::to('/contact', 'Contact'));
```

**Comment by willneumann** [comment]
That works perfectly. As a reference, here's the final code.
In Service Provider:

> use Menu;
use Spatie\Menu\Link;

> public function register()
     {
         app()->instance('menu.main', Menu::new()
            ->add(Link::to('/', 'Home'))
            ->add(Link::to('/about', 'About'))
        );
    }

In Controller (to add additional item):

> use Menu;
use Spatie\Menu\Link;

> app('menu.main')->add(Link::to('/contact', 'Contact'));

In a View:
> {{ app('menu.main') }}
