### ISSUE TITLE
[Feature Request] Allow Blade inside link names

### ISSUE THREAD

**Issue by randohinn** [spatie/laravel-menu#55]
I'm proposing this feature request for allowing the inclusion and therefore procesing of blade inside link titles, if at all possible. For example, try combining this with @adamwathan's `blade-svg` project. You'd get something like this in your code..

```php
 Menu::macro('main_logged_in', function () {
            return Menu::new()
                ->route('home', '@svg("folder-outline") Decks')
                ->route('home', '@svg("buoy") Support')
                ->setActiveFromRequest();
 });
```

Unfortunately, here Adam's package stops working, since the blade syntax is not being processed anymore. What comes out is this

![the result](http://puu.sh/wR58r/6fbcb37551.png)

What I'd really like is for the svg's to be displayed from Adam's package, and therefore possibly any other blade to be allowed to be in titles.

**Comment by sebastiandedeyne** [comment]
We're not planning to add Blade support to the strings here.

In the case of Adam's library, you could use the helper function it ships with.

```
->route('home', svg_image('folder_outline') . ' Decks')
```

**Comment by randohinn** [comment]
@sebastiandedeyne Ok, thanks! But please, change your workaround to be this for future askers, as this is what actually works:

```
 ->route('home', svg_image('folder-outline')->toHtml() . ' Decks')
 ->route('home', svg_image('buoy')->toHtml() . ' Support')
```
