### ISSUE TITLE
BROKEN! Invalid use Statement in VIew.php

### ISSUE THREAD

**Issue by sgc-fireball** [spatie/laravel-menu#57]
File: `vendor/spatie/laravel-menu/src/View.php`
Line: `use Spatie\HtmlElement\Attributes;`

Did you mean `\Spatie\Menu\Html\Attributes`?

**Comment by mpociot** [comment]
You removed the `html-element` dependency in the `menu` package with this commit:
https://github.com/spatie/menu/commit/02cc1c90bb51ec59b5bd37c5ed598c0a701d77fb

But it still gets referenced in this package.

**Comment by sebastiandedeyne** [comment]
Sorry about this! Tagged a fix in 2.1.3 :)
