### ISSUE TITLE
[QUESTION] Add menu items in different modules

### ISSUE THREAD

**Issue by heikobihlmaier** [spatie/laravel-menu#6]
Hello,

I have a question. Currently I use modules to make my application more encapsulated.

For example I have to following modules
* Core
* Page
* User
* Settings

Now I want that my backend menu is more flexibel. So I want to add menu points via service provider of the modul.

I create the menu within the "Core"-Modul. 
Can u help me, how I can do that ?

Greetings.

**Comment by sebastiandedeyne** [comment]
I'm not sure I understand what you mean, could you provide a code examples?

You can save the entire menu in a variable, so you could bind seperate instances to the IoC in various service providers if that would help.

**Comment by ttomdewit** [comment]
@sebastiandedeyne Does this mean one can programmatically add items to the `main` menu, for example? I am researching this package and hadn't noticed such option yet.

> I'm not sure I understand what you mean, could you provide a code examples? You can save the entire menu in a variable, so you could bind seperate instances to the IoC in various service providers if that would help.
