### ISSUE TITLE
Could we downgrade php requirement to php 5 ?

### ISSUE THREAD

**Issue by frdteknikelektro** [spatie/laravel-menu#61]
Could we downgrade php requirement to php 5 ?

**Comment by sebastiandedeyne** [comment]
Sorry, we're not supporting PHP 5 anymore for our packages. All major frameworks and libraries are also moving to PHP 7 this year.

Freek wrote a blog post on why we're not maintaining any PHP 5 packages anymore in case you're interested: https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/
