### ISSUE TITLE
Set `a class` to active, rather than `li class`

### ISSUE THREAD

**Issue by ghost** [spatie/laravel-menu#65]
Is it possible to setup a menu as per title? Bootstrap 4's pill navigation uses `active` differently to what's usually used, and sets active as part of the `a` attribute instead of the `li` attribute.

**Comment by sebastiandedeyne** [comment]
This isn't implemented now. I'd accept a PR that adds this, but it might be complex with the current setup of the package. Either way I'd like to have this in the next major version, no ETA though.

**Comment by sebastiandedeyne** [comment]
There's a PR open that does this, it'll be added soon. Follow #71 for updates :)

https://github.com/spatie/menu/pull/64
