### ISSUE TITLE
How to set active Laravel menu by route name

### ISSUE THREAD

**Issue by baraear** [spatie/laravel-menu#67]
Like topic header I don't know way to set active menu in Laravel

Sorry this is not issue might I'll be good for someone if my quest has been get back

**Comment by sebastiandedeyne** [comment]
Hi @baraear,

There's no convenience method for this. You could however write your own callable in `setActive` which compares the url with a route name.

See https://docs.spatie.be/menu/v2/items-in-depth/active-items#determining-the-active-items-with-a-callable
