### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by bishopm** [spatie/laravel-menu#71]
Thanks for this package :)

Are there plans to update it to accommodate the slightly different menu structure in Bootstrap 4?

**Comment by sebastiandedeyne** [comment]
There's a pull request in progress, I'll update this issue when it's released :)

https://github.com/spatie/menu/pull/64

**Comment by sebastiandedeyne** [comment]
See `spatie/menu` v2.5's release notes, this is now possible :)

https://github.com/spatie/menu/releases/tag/2.5.0
