### ISSUE TITLE
Change Menu::new() function name

### ISSUE THREAD

**Issue by Phil795** [spatie/laravel-menu#73]
For my PHP obfuscator and linter it would be better if the static functions of the Menu class were not called "new()". Can you please rename them for future versions?

**Comment by sebastiandedeyne** [comment]
Sorry, `new` is a valid method name in PHP, this sounds more like an issue that should be opened in the repo of your obfuscator or linter.

**Comment by Phil795** [comment]
However, the obfuscator must take `new` into consideration so as not to confuse it with the method.

The `new` method is valid, but another expression would be desirable. 
http://php.net/manual/en/reserved.keywords.php

But I also understand that change can be confusing.
