### ISSUE TITLE
Custom $activeClass and $exactActiveClass

### ISSUE THREAD

**Issue by jadamec** [spatie/laravel-menu#86]
Hello there,
how could I change the variables $activeClass and $exactActiveClass? My admin templates need a little bit different class for showing an active menu item. Thank you!

**Comment by sebastiandedeyne** [comment]
You can use the `setActiveClass` and `setExactActiveClass` methods.

```php
Menu::new()
    ->setActiveClass('active')
    ->setExactActiveClass('exact-active');
```
