### ISSUE TITLE
show submenu based on some condition

### ISSUE THREAD

**Issue by ritterg** [spatie/laravel-menu#89]
I have a menu (including submenu) based on "Bootstrap Menu" example from documentation.
* Users
* Events
  * Upcoming Events
  * Past Events
* Admin

Is it possible to show the submenu "Events" (including header "Events") only if some condition is true, e.g. show only if user is logged in?
Something like ->submenuIf()

**Comment by atymic** [comment]
There is a `submenuIf` method:
https://github.com/spatie/menu/blob/master/src/Menu.php#L242-L249

**Comment by ritterg** [comment]
Thanks, does exactly what I was looking for.
I looked through the documentation at https://docs.spatie.be/menu/v2/introduction/, but couldn't find it.
