### ISSUE TITLE
[PROPOSAL] AddView

### ISSUE THREAD

**Issue by lukasoppermann** [spatie/laravel-menu#9]
I did not find an easy way to add a view to the menu.

I am thinking about using this package and I have some more complicated menu items, that are more than just a link. I store those items in separate views, which is why adding a view as a menu item would be good.

Maybe something like this:

```php
Menu::new()
  ->action('HomeController@index', 'Home')
  ->addView('menu.viewFile', $viewData);
```

I think currently it would be possible to pass a `view('menu.viewFile', $viewData)->render()` to the `add()` method? But I think this would be a nicer way to add it.

Of course I just realise, that `setActiveFromRequest` would not work with a rendered view, would it? This would possible make it even more useful, as some logic for this could be included.

**Comment by freekmurze** [comment]
Seems like a good idea, what do you think @sebastiandedeyne ?

**Comment by lukasoppermann** [comment]
Some more ideas for this.

Maybe as a third (optional) parameter, a user could pass in a `url`. If this `url` matches the one from the request the view could get an additional variable `is_active` which would be `true`.

Maybe it would make sense to always provide `is_active`, but set it to `false` normally.

This way one could build the activation logic into the view itself, and you would not have to worry about anything.

**Comment by sebastiandedeyne** [comment]
I like this idea. First thing that comes to mind would be adding another `Item` implementation (like `Link` and `Html`) called `View`, that way we could also store active/inactive logic in an object.

Will tinker around with the idea later this week :+1:

**Comment by lukasoppermann** [comment]
Hey @sebastiandedeyne,

do you think it would be possible to add the `prefix` if any is added, to the view parameters? You could just merge it into the array as something like `menu_prefix`. Would be pretty handy. 👍

**Comment by lukasoppermann** [comment]
Hey @sebastiandedeyne , do you already have something here? Something I could test maybe?

**Comment by sebastiandedeyne** [comment]
Already got some stuff on master. Probably gonna finalise tomorrow.

https://github.com/spatie/laravel-menu/commit/41c1d173a68ee1a5d8cb996beab607a324bf7b1e

**Comment by lukasoppermann** [comment]
Awesome. 👍 Well, I guess I can wait until tomorrow. 😁

**Comment by lukasoppermann** [comment]
Hey, of course I could not wait and tested it out. It works fine, so far, however I am having the same issue I have with the HTML. You can not assign a url, so auto-activation via `setActiveFromRequest` will not work. 😢 

Additionally while the `setActive` and `setInActive` methods provide for a nice reading api, it makes it impossible to nicely add an action method programmatically, like so:

```php
View::create('menu.item')->setActive(app('request')->url() === '/my-route');
```

This would have been an ugly, but working, workaround for the missing url from the `View` and `Html` class. 

To address this, could you please, please, please 😄  add an optional parameter to the setActive method which is a boolean?

So I can do:

```php
...->setActive(true); // = active
...->setActive(false); // = inactive
``` 

The default value for the parameter would be `true` so that this change would not effect the API or the package in any bc breaking way.

**Comment by sebastiandedeyne** [comment]
I have two beta versions tagged for v2:

```
spatie/menu: 2.0.0-beta.3
spatie/laravel-menu: 2.0.0-beta.2
```

Both have updated changelogs already:

- https://github.com/spatie/menu/blob/master/CHANGELOG.md
- https://github.com/spatie/laravel-menu/blob/master/CHANGELOG.md

Feel free to give them a spin, I'd appreciate any feedback!

**Comment by lukasoppermann** [comment]
On it, awesome. 🎉

**Comment by lukasoppermann** [comment]
Hey @sebastiandedeyne it works pretty nice so far. However what I did not quite get is the `determineActiveForUrl`. I can not use it like so:

```php
->view('menu.item', [...])->determineActiveForUrl('/test')
```

Do I need to create a subitem and add the `Activatable` trait?

**Comment by sebastiandedeyne** [comment]
My issue with adding the interface is that it forces you to add a url even if it doesn't have one, or has multiple (e.g. if you're using a view for a section in the menu with multiple links).

Possible solutions:

- Slightly overhaul `HasUrl`, and allow the `url` method to return null, so everything can implement the trait but doesn't necessarily need the url. Feels kind of weird of having a `HasUrl` interface that actually means `MightHaveUrl` though.
- Check the view data for a `url` key, and use it as the url in `determineActiveForUrl` if it exists. This way it doesn't need to implement the interface, and the url is optional. This solution only works for view though, not for other url-less implementations like `Html`

**Comment by lukasoppermann** [comment]
I totally understand you issue. Personally I would think that the `CanHaveUrl` would actually be a pretty good.

I don't know your use cases, but I would image, that most people will use `html` and `view` for more complex menu items. Rather than just for headers, etc. (I use it for both).

Adding an icon to the menu already means you need to use a view, at least if you use `svgs` with a `use` statement. Personally I could not use `link` once, because it is just to opinionated for a little more fancy menus. 😄  

I think it is perfectly sensible to have a very strict and simple `link` implementation, like the one now implemented, however, seeing that for very small changes to this you will already need to use a view, I would argue that using views as link-elements is at least 50% of the use case. So adding a `CanHaveUrl` would be pretty nice.

**Comment by sebastiandedeyne** [comment]
As you've already seen, the url logic has been moved to the `Activatable` interface, which allows any item to have a url :)

In the case of view, if you pass a url to the `$data`, it will be used to check if it's currently active.

https://github.com/spatie/laravel-menu/blob/master/tests/ViewTest.php#L30

Tagged new versions (`spatie/menu:2.0.0-beta.4`, `spatie/laravel-menu:2.0.0-beta.3`). I think that wraps up the changes, all I still need to do is update the docs site!

**Comment by lukasoppermann** [comment]
Awesome! 😀 I will test it out today.

Does this mean if I were to create an item which uses `Activatable` I can also use `setUrl` and it would work? Or is `setUrl` not supposed to be used from the outside?

**Comment by sebastiandedeyne** [comment]
Correct, `setUrl` can also be used from the outside

**Comment by lukasoppermann** [comment]
Hey @sebastiandedeyne I might have found a bug 🐛

I get this error:

```
Undefined property: Spatie\Menu\Laravel\View::$url (View: /var/www/html/resources/views/teamwork/index.blade.php)
```

I can produce it by creating a menu with views, some of which do not have a `url` (although I am not sure this is important).

If I add `->setActiveFromRequest()` I get this error. Removing it means no error.

It does not happen if the url is provided in any item. Do you have any idea? Maybe it is misconfiguration on my part?

**Comment by sebastiandedeyne** [comment]
Forgot to declare the property on the class, so it only existed if it was explicitly set.

Fixed in `spatie/laravel-menu:2.0.0-beta.4` 🎉

**Comment by lukasoppermann** [comment]
Wow, that was fast!

**Comment by lukasoppermann** [comment]
Hey @sebastiandedeyne I am using it for a while now and it works fine. You can probably close this and tag a release. Thank you.

**Comment by sebastiandedeyne** [comment]
Good to hear!

Yeah the code's ready for a tag, just need to find some time to polish up the docs first :)

**Comment by lukasoppermann** [comment]
Ahh, yes, makes sense.
