### ISSUE TITLE
Html setAttribute 

### ISSUE THREAD

**Issue by LPABelgium** [spatie/laravel-menu#90]
Laravel : 5.8
Laravel-Menu : 3.3
***

Hi Freek,

First, thanks for all your really usefull Laravel Packages !

So, perhaps I didn't saw it in the doc, but it seems not possible to set an attribute to Html::raw().

I have something  like that : 
```
$menu = Menu::new()
   ->addClass('col-12 list-unstyled')
   ->setAttribute('role', 'menu');

$menu->addIf(
   Auth::guard('cms')->user()->can('setting'),
   Html::raw('<a href="'.route('cms.settings').'"><i class="mdi mdi-cogs"></i> Params</a>')
      ->setActive()
      ->setAttribute('role', 'menuitem');
);

$menu->add(
   Html::raw('<a href="'.route('cms.home').'"><i class="mdi mdi-view-dashboard-outline"></i> Dashboard</a>')
);
```

"setActive()" is effective on Html::raw() but "setAttribute()" return an error.
It seems not to be possible to add attribute as we can on Link.

Thanks (from Luik ;) )

**Comment by sebastiandedeyne** [comment]
`setAttribute` is not available on `Html::raw`, because `Html::raw` gives you full control of the HTML.

We don't parse the HTML you pass, so we can't modify it either. You'll need to add it yourself:

```
$menu->add(
   Html::raw('<a href="'.route('cms.home').'" role="menuitem"><i class="mdi mdi-view-dashboard-outline"></i> Dashboard</a>')
);
```

**Comment by LPABelgium** [comment]
Perhaps I missunderstand you but... How could I add the attribute on the `<li>` tag ??

Html::raw() generates the content of the `<li>` but not the `<li>` itself. So the solution you gave me is not the one I look at for.

The attribute `role="menuitem"` must be on `<li>`. Final generated HTML should be :

```
<ul class="col-12 list-unstyled" role="menu">
   <li role="menuitem">
      <a href="'.route('cms.home').'" class="active"><i class="mdi mdi-view-dashboard-outline"></i> Dashboard</a>
   </li>
</ul>
```
If I set the attribute like this : 

```
$menu = Menu::new()
   ->addClass('col-12 list-unstyled')
   ->setAttribute('role', 'menu');

$menu->addIf(
   Auth::guard('cms')->user()->can('setting'),
   Html::raw('<a href="'.route('cms.settings').'"><i class="mdi mdi-cogs"></i> Params</a>')
      ->setActive();
)->setAttribute('role', 'menuitem');
```
It's the `<ul>` which takes the attribute `role="menuitem"`, not the `<li>`

And doing this : 

```
$menu = Menu::new()
   ->addClass('col-12 list-unstyled')
   ->setAttribute('role', 'menu');

$menu->addIf(
   Auth::guard('cms')->user()->can('setting'),
   Html::raw('<a href="'.route('cms.settings').'"><i class="mdi mdi-cogs"></i> Params</a>')
      ->setActive()
      ->setAttribute('role', 'menuitem');
);
```
generate an error...

`setAttribute()` should be added on `Html` as the same way `setActive()` work, no ?

So, how can I achieve my goal (add `<li>` tag in `Html::raw()` doesn't work too... it creates an empty `<li>`)?

**Comment by sebastiandedeyne** [comment]
Ahha, in that case it’s the `setParentAttribute` method you’re looking for, which should be available on all item types :)

**Comment by LPABelgium** [comment]
Great ;) Thanks !
